\input texinfo @c -*-texinfo-*-
@iftex
@finalout
@end iftex
@comment $Id: imail.texinfo,v 1.1 2000/07/07 20:53:07 cph Exp $
@comment %**start of header (This is for running Texinfo on a region.)
@setfilename imail.info
@settitle IMAIL User's Manual
@comment %**end of header (This is for running Texinfo on a region.)
@setchapternewpage odd
@syncodeindex vr cp
@syncodeindex fn cp
@syncodeindex ky cp

@ifinfo
This file documents the use of MIT Scheme.

Copyright @copyright{} 2000 Massachusetts Institute of Technology

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.1 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with no Front-Cover Texts, and with no Back-Cover
Texts.  A copy of the license is included in the section entitled "GNU
Free Documentation License".
@end ifinfo

@titlepage
@title{IMAIL User's Manual}
@subtitle Edition 0.1
@subtitle 7 July 2000
@author by Chris Hanson

@page

@vskip 0pt plus 1filll
Copyright @copyright{} 2000 Massachusetts Institute of Technology

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.1 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with no Front-Cover Texts, and with no Back-Cover
Texts.  A copy of the license is included in the section entitled "GNU
Free Documentation License".
@end titlepage

@node Top, Introduction, (dir), (dir)

@ifinfo
This Info file is the user's guide for the @sc{imail} email reader, a
part of MIT Scheme.  It describes how to use @sc{imail}, what features
it provides for viewing and editing email, and how to customize its
optional behavior.
@end ifinfo

@menu
* Introduction::                
* Getting Started::             
* Concepts::                    
* Commands::                    
* Variables::                   
* Index::                       
@end menu

@node Introduction, Getting Started, Top, Top
@unnumbered Introduction

@cindex Internet Message Access Protocol
@cindex IMAP
@sc{imail} is a program for reading electronic mail.  It uses the
@dfn{Internet Message Access Protocol} (@sc{imap}) to access mail that
is stored on a server, from which @sc{imail} fetches individual messages
on demand.  The server may have many different @dfn{folders} in which
messages are stored, arranged in a hierarchical structure like that of a
file system.  Messages are easily moved or copied from one folder to
another.

@cindex Multipurpose Internet Mail Extensions
@cindex MIME
@sc{imap} also supports the @dfn{Multipurpose Internet Mail Extensions}
(@sc{mime}), which allows the sending and receiving of
@dfn{attachments}.  The @sc{imap} protocol supports this by allowing you
to fetch some parts of a mail message while leaving others on the
server.  So, for example, if you receive a message containing a large
attachment, it is possible to view the text of the message without
waiting for the attachment to be fetched from the server; the attachment
is fetched only if you want to view or save it.  If you aren't
interested in the attachment, you can delete the message without ever
fetching it from the server.

@cindex RMAIL
In addition to these features, @sc{imail} provides a user interface very
similar to that of the Emacs @sc{rmail} mail reader.  @sc{imail}
supports most of the same commands and has most of the same key bindings
as @sc{rmail}.  @sc{imail} is primarily intended to be an @sc{rmail}
replacement for people who wish to read their mail using an @sc{imap}
server.  @sc{imail} can also read and write @sc{rmail} files and unix
mail (mbox) files, and provides the ability to copy messages from such a
file to an @sc{imap} folder, or vice versa; this greatly simplifies the
transition from @sc{rmail} to @sc{imail} for those of us who have large
amounts of mail stored in files.

@node Getting Started, Concepts, Introduction, Top
@chapter Getting Started

At present, @sc{imail} has only a very simple mechanism for connecting
to an @sc{imap} server: it makes an unencrypted connection to the
server, and logs in with a user name and a password.  In the near
future, we will implement @sc{cram-md5} authentication.  However, we
have no plans to offer encryption for the connection.

Here at MIT, we connect to our server using stunnel
(@code{http://www.stunnel.org/}) to provide end-to-end encryption.  This
provides connection security without the need to integrate the
encryption into the client or the server.

To use @sc{imail}, you must create an Edwin init file, called
@file{~/.edwin} on unix machines, and @file{edwin.ini} on Windows or
OS/2 machines.  This file contains arbitrary Scheme expressions that are
evaluated in the Edwin environment when Edwin is started.  In addition
to any other customizations you put in this file, you must include the
following expression:

@example
(load-option 'imail)
@end example

Next, you must tell Edwin where to find your @sc{imap} server, by
setting some variables.  Here is an example:

@example
(set-variable! imail-default-imap-server "imap.foo.org")
@end example

@noindent
Note that this is syntactically similar to Scheme's @code{set!} special
form, but that it modifies the value of an Edwin editor variable rather
than a Scheme variable.  There are several other variables that control
how @sc{imail} connects to the server.  @xref{Variables} for a complete
list.

By default, @sc{imail} tries to connect to @samp{localhost} using port
@code{143}, and to log in using the user name that you are logged in as.
This is the right default if you are using stunnel on the client.

After you are finished creating the init file, you can either restart
Edwin, or you can load the file using @kbd{M-x load-file}.

At this point, you are ready to run @sc{imail}.  To start @sc{imail} and
read the mail in the @samp{inbox} folder on your @sc{imap} server, type
@kbd{M-x imail}.

@node Concepts, Commands, Getting Started, Top
@chapter Concepts

@node Commands, Variables, Concepts, Top
@chapter Commands

@node Variables, Index, Commands, Top
@chapter Variables

@node Index,  , Variables, Top
@unnumbered Index
@printindex cp

@contents
@bye
