#!/bin/sh

tex scheme.texinfo
texindex scheme.cp scheme.fn scheme.ky scheme.pg scheme.tp scheme.vr
tex scheme.texinfo
texindex scheme.cp scheme.fn scheme.ky scheme.pg scheme.tp scheme.vr
tex scheme.texinfo
# hopefully by now all the references have reached their correct pages
