#!/bin/bash

# Usage: check-crefs [BUILD-DIR]
# If no BUILD-DIR, uses dir named "build" in root.

set -e

if (( ${#} > 0 )); then
    cd "${1}"
else
    cd "$(dirname "${0}")"/../build
fi
for f in $(find * -type f -name \*-unx.crf); do
    echo '>>>>' "${f}"
    cat "${f}"
    echo
done
