#!/bin/sh
# Script to generate standard runtime band from binaries.
# $Header: /Users/cph/tmp/foo/mit-scheme/mit-scheme/etc/make_runtime,v 1.3 1990/12/12 03:10:20 cph Exp $
cd runtime
exec ../microcode/scheme -library ../lib -fasl make.bin < ../etc/mkband.scm
