#!/bin/csh -f

set scheme=`pwd`

if (! -e $scheme/microcode/Psbtobin ) then
  (cd $scheme/microcode; make Psbtobin)
endif

cd $scheme/psb
foreach i (`find * -type d -print | xargs echo`)
  if (! -d $scheme/$i) then
    echo "mkdir $scheme/$i"
    mkdir $scheme/$i
  endif
  cd $scheme/psb/$i
  foreach j (*)
    if (-f $j) then
      echo "Psbtobin $scheme/$i/$j"
      $scheme/microcode/Psbtobin < $j >! $scheme/$i/$j
    endif
  end
end
