#!/bin/csh -f

set scheme=`pwd`

if (! -e $scheme/microcode/Psbtobin ) then
  (cd $scheme/microcode; make Psbtobin)
endif

cd $scheme/psb
foreach i (*)
  cd $scheme/psb/$i
  foreach j (*)
    echo "Psbtobin $scheme/$i/$j"
    $scheme/microcode/Psbtobin < $j >! $scheme/$i/$j
  end
end
