;;; -*- Scheme -*-

(define (pack-edwin output)
  (pack-binaries output
                 '(("\\scheme\\edwin"
		    "make.com"
		    "edwin.bcon"
		    "edwin.bldr"
		    "edwin.bad"
		    "utils.com"
		    "nvector.com"
		    "ring.com"
		    "strtab.com"
		    "strpad.com"
		    "macros.com"
		    "class.com"
		    "clscon.com"
		    "clsmac.com"
		    "xform.com"
		    "paths.com"
		    "struct.com"
		    "grpops.com"
		    "regops.com"
		    "motion.com"
		    "search.com"
		    "image.com"
		    "comman.com"
		    "comtab.com"
		    "modes.com"
		    "buffer.com"
		    "bufset.com"
		    "undo.com"
		    "display.com"
		    "screen.com"
		    "winren.com"
		    "window.com"
		    "utlwin.com"
		    "bufwin.com"
		    "bufwfs.com"
		    "bufwiu.com"
		    "bufwmc.com"
		    "comwin.com"
		    "modwin.com"
		    "buffrm.com"
		    "edtfrm.com"
		    ;; "xterm.com"
		    "key.com"
		    "termcap.com"
		    "ansi.com"
		    "tterm.com"
		    "edtstr.com"
		    "editor.com"
		    "curren.com"
		    "simple.com"
		    "debuge.com"
		    "calias.com"
		    "modlin.com"
		    "input.com"
		    "prompt.com"
		    "comred.com"
		    "bufinp.com"
		    "bufout.com"
		    "winout.com"
		    "things.com"
		    "tparse.com"
		    "syntax.com"
		    "regexp.com"
		    "rgxcmp.com"
		    "linden.com"
		    "dos.com"
		    "fileio.com"
		    "dosproc.com"
		    "argred.com"
		    "autold.com"
		    "autosv.com"
		    "basic.com"
		    "bufcom.com"
		    "bufmnu.com"
		    "c-mode.com"
		    "cinden.com"
		    "comint.com"
		    ;; "compile.com"
		    "debug.com"
		    "dired.com"
		    "evlcom.com"
		    "filcom.com"
		    "fill.com"
		    "hlpcom.com"
		    ;; "info.com"
		    "intmod.com"
		    "keymap.com"
		    "kilcom.com"
		    "kmacro.com"
		    "lincom.com"
		    "lspcom.com"
		    ;; "malias.com"
		    "motcom.com"
		    ;; "occur.com"
		    ;; "rcs.com"
		    "reccom.com"
		    "regcom.com"
		    "replaz.com"
		    ;; "rmail.com"
		    ;; "rmailsrt.com"
		    "schmod.com"
		    ;; "sendmail.com"
		    "sercom.com"
		    "iserch.com"
		    ;; "shell.com"
		    "tagutl.com"
		    "texcom.com"
		    "wincom.com"
		    "scrcom.com"
		    ;; "xcom.com"
		    "modefs.com"
		    "rename.com"
		    "loadef.com"
		    ;; "bochser.com"
		    ;; "bochsmod.com"
		    ;; "notify.com"
		    ;; "outline.com"
		    ))))