#!/bin/sh
#
#	Update RCS.log file in background.  no arguments
#
#	Currently being run daily from cph crontab on aarau

PATH=/usr/contrib/bin:/usr/local/bin:/usr/bin:/bin
export PATH
umask 002

bgx -ioe /scheme/etc/update-rcs-log scheme -large -no-init-file
