#!/bin/sh

# Update Scheme ChangeLog files.
# Run daily from cph crontab on aarau.

umask 002

exec > /scheme/etc/update-rcs-log.out 2>&1

export PATH="/usr/local/bin:${PATH}"

GOPTS_SCHEME="-d :pserver:anoncvs@subversions.gnu.org:/cvsroot/mit-scheme"
UM="/scheme/v7/src/etc/usermap"
O="ChangeLog"
N="${O}.new"

generate_log_gopts ()
{
    cd "${1}"
    cvs2cl --global-opts "${2}" --revisions --usermap "${UM}" --stdout > "${N}"
    if cmp "${N}" "${O}"; then
	rm -f "${N}"
    elif [ -s "${N}" ]; then
	mv -f "${N}" "${O}"
    else
	echo "Discarding zero-length log."
	rm -f "${N}"
    fi
}

generate_log_gopts /scheme/v7/doc "${GOPTS_SCHEME}"
generate_log_gopts /scheme/v7/src "${GOPTS_SCHEME}"
generate_log_gopts /scheme/etc "${GOPTS_SCHEME}"

generate_log ()
{
    cd "${1}"
    cvs2cl --revisions --usermap "${UM}" --stdout > "${N}"
    if cmp "${N}" "${O}"; then
	rm -f "${N}"
    else
	mv -f "${N}" "${O}"
    fi
}

generate_log /gunk/hlsim/doc
generate_log /gunk/hlsim/src
