#!/bin/sh

# Copyright (C) 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994,
#     1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004,
#     2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014,
#     2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022 Massachusetts
#     Institute of Technology
#
# This file is part of MIT/GNU Scheme.
#
# MIT/GNU Scheme is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# MIT/GNU Scheme is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with MIT/GNU Scheme; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
# 02110-1301, USA.

# Script to create "liarc-vars" and "liarc-rules", which configure
# substitutes into the Makefile for the C back end, and to refresh
# "makegen/sources.am".  Requires `gcc' and `scheme'.

# Don't leave the outputs around in case anything fails.

clean_outputs=yes

clean ()
{
  if [ "${clean_outputs}" = yes ]; then
    rm -f liarc-vars liarc-rules
  fi
}

trap clean EXIT INT TERM

# Generate "config.h".

./configure --disable-native-code ${1+"$@"} || exit $?

# Requires "config.h", because dependencies are generated by running
# GCC -M on the source files, which refer to "config.h".

"${MIT_SCHEME_EXE:-mit-scheme}" --batch-mode --no-init-file <<EOF
(begin
  (load "makegen/makegen.scm")
  (generate-makefile))
EOF

# If we succeeded, don't delete the outputs on exit.

if [ $? -eq 0 ]; then
  clean_outputs=no
fi

# Clean up.

make distclean
