#!/bin/sh -e
# /usr/lib/emacsen-common/packages/remove/mit-scheme

FLAVOR="${1}"
PACKAGE="mit-scheme"
FILES="xscheme.elc"

if [ "${FLAVOR}" != "emacs" ]; then
    echo "remove/${PACKAGE}: purging byte-compiled files for ${FLAVOR}"
    rm -rf "/usr/share/${FLAVOR}/site-lisp/${PACKAGE}"
fi
