#!/bin/bash
set -eu
SCRIPT=${0}
case ${SCRIPT} in
    /*)
        HERE=$(dirname "${SCRIPT}")
        ;;
    *)
        HERE=$(dirname "$(pwd)/${SCRIPT}")
        ;;
esac
MIT_SCHEME_EXE=${HERE}/microcode/scheme
MITSCHEME_INF_DIRECTORY=${HERE}/lib
MITSCHEME_LIBRARY_PATH=${HERE}/lib
export MIT_SCHEME_EXE
export MITSCHEME_INF_DIRECTORY
export MITSCHEME_LIBRARY_PATH
exec "${MIT_SCHEME_EXE}" "${@}"
