/* -*-C-*-
   System file for 386BSD

$Id: 386bsd.h,v 1.3 1999/01/02 06:11:34 cph Exp $

Copyright (c) 1993-1999 Massachusetts Institute of Technology

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or (at
your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
*/

#define C_SWITCH_SYSTEM -I/usr/X11R6/include

#define C_OPTIMIZE_SWITCH -O6

#define LIBX11_MACHINE -L/usr/X11R6/lib

#define LIBS_TERMCAP -ltermcap

#define LIB_DEBUG

#define ALTERNATE_M4 s/ultrix.m4

/* Use the built-in files <limits.h> and <float.h> rather than those
   generated by the "hard-par" program.  */
#define USE_BUILT_IN_LIMITS_FILES

#ifdef __bsdi__
/* Compile using shared libraries and GCC v2.  */
#define ALTERNATE_CC shlicc2
#endif

#ifdef __FreeBSD__
#define ALTERNATE_CC gcc
#endif
