/* -*-C-*-
   System file for FreeBSD

$Id: freebsd.h,v 1.3 2000/02/01 04:08:27 cph Exp $

Copyright (c) 1993-2000 Massachusetts Institute of Technology

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or (at
your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
*/

#ifdef __ELF__

#define C_SWITCH_SYSTEM -I/usr/X11R6/include

#define LIBX11_MACHINE -L/usr/X11R6/lib

#define LIB_DEBUG

#define ALTERNATE_M4 s/ultrix.m4

#define LINUX_STATIC_LIBS(libs) -Xlinker -Bstatic libs -Xlinker -Bdynamic

#define M4_SWITCH_SYSTEM -P "define(SUPPRESS_LEADING_UNDERSCORE,1)"

#define LIBS_TERMCAP LINUX_STATIC_LIBS (-ltermcap)
#define HAVE_TERMINFO

#define LD_SWITCH_SYSTEM -export-dynamic

/* Use the built-in files <limits.h> and <float.h> rather than those
   generated by the "hard-par" program.  */
#define USE_BUILT_IN_LIMITS_FILES

#else /* not __ELF__ */

#include "386bsd.h"

#endif /* not __ELF__ */
